import .cardea_python.heartRateAnalysis

hra = heartRateAnalysis.heartRateAnalysis("6KT96H", "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2S1Q5NkgiLCJhdWQiOiIyMkQ3QjkiLCJpc3MiOiJGaXRiaXQiLCJ0eXAiOiJhY2Nlc3NfdG9rZW4iLCJzY29wZXMiOiJyd2VpIHJociByYWN0IHJudXQgcnNsZSIsImV4cCI6MTUzNzczNjkyNSwiaWF0IjoxNTM3NzA4MTI1fQ.AEOGSVFjOfu3dBhOP6Tu6siDukKvV9nAqVHc4575ko4")

print(hra.heartRate_and_exercise(12))
